{"name": "test_login", "status": "broken", "statusDetails": {"message": "AttributeError: 'RegisterUser' object has no attribute 'input_data_first_name'", "trace": "browser = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"1088c277c20fdab84deb3e6e1144a944\")>\n\n    @pytest.mark.usefixtures(\"browser\")\n    def test_login(browser):\n        logger.info('====== Started: {} ======'.format(int(time.time())))\n        try:\n            with allure.step('Navigating to Main Page and clicking My Account'):\n                logger.debug('Navigating to Main Page')\n                main_page = MainPage(browser)\n                logger.debug('Clicking My Account')\n                main_page.click_my_account()\n                take_screenshot(browser, 'Main Page - My Account')\n    \n            with allure.step('Clicking Register User'):\n                logger.debug('Clicking Register User')\n                main_page.click_register_user()\n                take_screenshot(browser, 'Main Page - Register User')\n    \n            with allure.step('Filling registration form'):\n                logger.debug('Filling registration form')\n                register_user = RegisterUser(browser)\n>               register_user.input_data_first_name()\nE               AttributeError: 'RegisterUser' object has no attribute 'input_data_first_name'\n\ntests/test_login.py:42: AttributeError"}, "steps": [{"name": "Navigating to Main Page and clicking My Account", "status": "passed", "attachments": [{"name": "Main Page - My Account", "source": "f0c2e680-8114-4105-b133-75d80d466e3a-attachment.png", "type": "image/png"}], "start": 1722155066379, "stop": 1722155067153}, {"name": "Clicking Register User", "status": "passed", "attachments": [{"name": "Main Page - Register User", "source": "7a5aebb2-4a91-4938-ab7e-7a35f5060739-attachment.png", "type": "image/png"}], "start": 1722155067153, "stop": 1722155068017}, {"name": "Filling registration form", "status": "broken", "statusDetails": {"message": "AttributeError: 'RegisterUser' object has no attribute 'input_data_first_name'\n", "trace": "  File \"/home/we/Desktop/Projects/Python/pyOtus/tests/test_login.py\", line 42, in test_login\n    register_user.input_data_first_name()\n"}, "start": 1722155068017, "stop": 1722155068017}], "attachments": [{"name": "Error", "source": "c60c5198-5a46-44c2-bce3-3ff99bc8a3a8-attachment.png", "type": "image/png"}, {"name": "log", "source": "12c10d9b-599d-47e6-932d-88cbc52c1ebd-attachment.txt", "type": "text/plain"}], "start": 1722155066379, "stop": 1722155068144, "uuid": "bab0ed36-a073-47b4-9893-6e9c6bbe25b2", "historyId": "a707b9555172d26c5c1ec2d556e674f3", "testCaseId": "a707b9555172d26c5c1ec2d556e674f3", "fullName": "tests.test_login#test_login", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('browser')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "we"}, {"name": "thread", "value": "4978-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}