{"name": "test_login", "status": "broken", "statusDetails": {"message": "AttributeError: 'RegisterUser' object has no attribute 'input_data_first_name'", "trace": "browser = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"6526ca171087a2d0003a2cccab2faf46\")>\n\n    @pytest.mark.usefixtures(\"browser\")\n    def test_login(browser):\n        logger.info('====== Started: {} ======'.format(int(time.time())))\n        try:\n            with allure.step('Navigating to Main Page and clicking My Account'):\n                logger.debug('Navigating to Main Page')\n                main_page = MainPage(browser)\n                logger.debug('Clicking My Account')\n                main_page.click_my_account()\n                take_screenshot(browser, 'Main Page - My Account')\n    \n            with allure.step('Clicking Register User'):\n                logger.debug('Clicking Register User')\n                main_page.click_register_user()\n                take_screenshot(browser, 'Main Page - Register User')\n    \n            with allure.step('Filling registration form'):\n                logger.debug('Filling registration form')\n                register_user = RegisterUser(browser)\n>               register_user.input_data_first_name()\nE               AttributeError: 'RegisterUser' object has no attribute 'input_data_first_name'\n\ntests/test_login.py:42: AttributeError"}, "steps": [{"name": "Navigating to Main Page and clicking My Account", "status": "passed", "attachments": [{"name": "Main Page - My Account", "source": "06519484-dd91-4797-8d9b-11c28aa1d3af-attachment.png", "type": "image/png"}], "start": 1722155921679, "stop": 1722155922464}, {"name": "Clicking Register User", "status": "passed", "attachments": [{"name": "Main Page - Register User", "source": "7d839def-5a20-4fd8-bc31-f34ad584176a-attachment.png", "type": "image/png"}], "start": 1722155922464, "stop": 1722155923303}, {"name": "Filling registration form", "status": "broken", "statusDetails": {"message": "AttributeError: 'RegisterUser' object has no attribute 'input_data_first_name'\n", "trace": "  File \"/home/we/Desktop/Projects/Python/pyOtus/tests/test_login.py\", line 42, in test_login\n    register_user.input_data_first_name()\n"}, "start": 1722155923304, "stop": 1722155923304}], "attachments": [{"name": "Error", "source": "2a5da046-a7a3-4150-adff-810fa0b45a72-attachment.png", "type": "image/png"}, {"name": "log", "source": "8e89626f-8c8a-4b34-97fa-d0e05792f30b-attachment.txt", "type": "text/plain"}], "start": 1722155921679, "stop": 1722155923415, "uuid": "177b6922-1889-405b-a170-9d87a274b607", "historyId": "a707b9555172d26c5c1ec2d556e674f3", "testCaseId": "a707b9555172d26c5c1ec2d556e674f3", "fullName": "tests.test_login#test_login", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('browser')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "we"}, {"name": "thread", "value": "7221-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}